#!/bin/bash

#Auto commit:
git commit -a -m "*auto ..."
SYNC_SERVER_NAME="sun"
REMOTE_MACHINE_NAME="piedone3"
DIRNAME=`pwd`
BRANCHNAME=`git branch | sed -e 's/\* //'`

git push sun ${BRANCHNAME}

ssh ${REMOTE_MACHINE_NAME} "cd ${DIRNAME}; cmake .; git fetch ${SYNC_SERVER_NAME}; if git pull --ff-only ${SYNC_SERVER_NAME} ${BRANCHNAME}; then if make; then ./test; fi; fi"
